# data_wilayah.py
DATA_KECAMATAN = [
    {
        "kecamatan": "Sragen",
        "daftar_wilayah": [
            {"nama": "Karang Tengah", "status": "Kelurahan"},
            {"nama": "Nglorog", "status": "Kelurahan"},
            {"nama": "Sine", "status": "Kelurahan"},
            {"nama": "Sragen Kulon", "status": "Kelurahan"},
            {"nama": "Sragen Tengah", "status": "Kelurahan"},
            {"nama": "Sragen Wetan", "status": "Kelurahan"},
            {"nama": "Kedungupit", "status": "Desa"},
            {"nama": "Tangkil", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Gemolong",
        "daftar_wilayah": [
            {"nama": "Gemolong", "status": "Kelurahan"},
            {"nama": "Kragilan", "status": "Kelurahan"},
            {"nama": "Kwangen", "status": "Kelurahan"},
            {"nama": "Ngembat Padas", "status": "Kelurahan"},
            {"nama": "Brangkal", "status": "Desa"},
            {"nama": "Geneng Duwur", "status": "Desa"},
            {"nama": "Jatibatur", "status": "Desa"},
            {"nama": "Jenalas", "status": "Desa"},
            {"nama": "Kalangan", "status": "Desa"},
            {"nama": "Kaloran", "status": "Desa"},
            {"nama": "Nganti", "status": "Desa"},
            {"nama": "Peleman", "status": "Desa"},
            {"nama": "Purworejo", "status": "Desa"},
            {"nama": "Tegaldowo", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Karangmalang",
        "daftar_wilayah": [
            {"nama": "Kroyo", "status": "Kelurahan"},
            {"nama": "Plumbungan", "status": "Kelurahan"},
            {"nama": "Guworejo", "status": "Desa"},
            {"nama": "Jurangjero", "status": "Desa"},
            {"nama": "Kedung Waduk", "status": "Desa"},
            {"nama": "Mojorejo", "status": "Desa"},
            {"nama": "Pelem Gadung", "status": "Desa"},
            {"nama": "Plosokerep", "status": "Desa"},
            {"nama": "Puro", "status": "Desa"},
            {"nama": "Saradan", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Gesi",
        "daftar_wilayah": [
            {"nama": "Blangu", "status": "Desa"},
            {"nama": "Gesi", "status": "Desa"},
            {"nama": "Pilangsari", "status": "Desa"},
            {"nama": "Poleng", "status": "Desa"},
            {"nama": "Slendro", "status": "Desa"},
            {"nama": "Srawung", "status": "Desa"},
            {"nama": "Tanggan", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Gondang",
        "daftar_wilayah": [
            {"nama": "Bumiaji", "status": "Desa"},
            {"nama": "Glonggong", "status": "Desa"},
            {"nama": "Gondang", "status": "Desa"},
            {"nama": "Kaliwedi", "status": "Desa"},
            {"nama": "Plosorejo", "status": "Desa"},
            {"nama": "Srimulyo", "status": "Desa"},
            {"nama": "Tegalrejo", "status": "Desa"},
            {"nama": "Tunggul", "status": "Desa"},
            {"nama": "Wonotolo", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Jenar",
        "daftar_wilayah": [
            {"nama": "Banyuurip", "status": "Desa"},
            {"nama": "Dawung", "status": "Desa"},
            {"nama": "Japoh", "status": "Desa"},
            {"nama": "Jenar", "status": "Desa"},
            {"nama": "Kandang Sapi", "status": "Desa"},
            {"nama": "Mlale", "status": "Desa"},
            {"nama": "Ngepringan", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Kalijambe",
        "daftar_wilayah": [
            {"nama": "Banaran", "status": "Desa"},
            {"nama": "Bukuran", "status": "Desa"},
            {"nama": "Donoyudan", "status": "Desa"},
            {"nama": "Jetiskarangpung", "status": "Desa"},
            {"nama": "Kalimacan", "status": "Desa"},
            {"nama": "Karangjati", "status": "Desa"},
            {"nama": "Keden", "status": "Desa"},
            {"nama": "Krikilan", "status": "Desa"},
            {"nama": "Ngebung", "status": "Desa"},
            {"nama": "Samberembe", "status": "Desa"},
            {"nama": "Saren", "status": "Desa"},
            {"nama": "Tegalombo", "status": "Desa"},
            {"nama": "Trobayan", "status": "Desa"},
            {"nama": "Wonorejo", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Kedawung",
        "daftar_wilayah": [
            {"nama": "Bendungan", "status": "Desa"},
            {"nama": "Celep", "status": "Desa"},
            {"nama": "Jenggrik", "status": "Desa"},
            {"nama": "Karang Pelem", "status": "Desa"},
            {"nama": "Kedawung", "status": "Desa"},
            {"nama": "Mojodoyong", "status": "Desa"},
            {"nama": "Mojokerto", "status": "Desa"},
            {"nama": "Pengkok", "status": "Desa"},
            {"nama": "Wonokerso", "status": "Desa"},
            {"nama": "Wonorejo", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Masaran",
        "daftar_wilayah": [
            {"nama": "Dawungan", "status": "Desa"},
            {"nama": "Gebang", "status": "Desa"},
            {"nama": "Jati", "status": "Desa"},
            {"nama": "Jirapan", "status": "Desa"},
            {"nama": "Karang Malang", "status": "Desa"},
            {"nama": "Kliwonan", "status": "Desa"},
            {"nama": "Krebet", "status": "Desa"},
            {"nama": "Krikilan", "status": "Desa"},
            {"nama": "Masaran", "status": "Desa"},
            {"nama": "Pilang", "status": "Desa"},
            {"nama": "Pringanom", "status": "Desa"},
            {"nama": "Sepat", "status": "Desa"},
            {"nama": "Sidodadi", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Miri",
        "daftar_wilayah": [
            {"nama": "Bagor", "status": "Desa"},
            {"nama": "Brojol", "status": "Desa"},
            {"nama": "Doyong", "status": "Desa"},
            {"nama": "Geneng", "status": "Desa"},
            {"nama": "Gilirejo", "status": "Desa"},
            {"nama": "Gilirejo Baru", "status": "Desa"},
            {"nama": "Girimargo", "status": "Desa"},
            {"nama": "Jeruk Soko", "status": "Desa"},
            {"nama": "Sunggingan", "status": "Desa"},
            {"nama": "Soko", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Mondokan",
        "daftar_wilayah": [
            {"nama": "Gemantar", "status": "Desa"},
            {"nama": "Jambangan", "status": "Desa"},
            {"nama": "Jekani", "status": "Desa"},
            {"nama": "Kedawung", "status": "Desa"},
            {"nama": "Pare", "status": "Desa"},
            {"nama": "Sono", "status": "Desa"},
            {"nama": "Sumberejo", "status": "Desa"},
            {"nama": "Tempelrejo", "status": "Desa"},
            {"nama": "Trombol", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Ngrampal",
        "daftar_wilayah": [
            {"nama": "Bandung", "status": "Desa"},
            {"nama": "Bener", "status": "Desa"},
            {"nama": "Gabus", "status": "Desa"},
            {"nama": "Karangudi", "status": "Desa"},
            {"nama": "Kebonromo", "status": "Desa"},
            {"nama": "Klandungan", "status": "Desa"},
            {"nama": "Ngarum", "status": "Desa"},
            {"nama": "Pilangsari", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Plupuh",
        "daftar_wilayah": [
            {"nama": "Cangkol", "status": "Desa"},
            {"nama": "Dari", "status": "Desa"},
            {"nama": "Gedongan", "status": "Desa"},
            {"nama": "Gentanbanaran", "status": "Desa"},
            {"nama": "Karang Anyar", "status": "Desa"},
            {"nama": "Karangwaru", "status": "Desa"},
            {"nama": "Karangtalun", "status": "Desa"},
            {"nama": "Kliwonan", "status": "Desa"},
            {"nama": "Manyarejo", "status": "Desa"},
            {"nama": "Ngasinan", "status": "Desa"},
            {"nama": "Pungsari", "status": "Desa"},
            {"nama": "Plupuh", "status": "Desa"},
            {"nama": "Sambirejo", "status": "Desa"},
            {"nama": "Sidokerto", "status": "Desa"},
            {"nama": "Somomorodono", "status": "Desa"},
            {"nama": "Tegalrejo", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Sambirejo",
        "daftar_wilayah": [
            {"nama": "Blimbing", "status": "Desa"},
            {"nama": "Jetis", "status": "Desa"},
            {"nama": "Kadipiro", "status": "Desa"},
            {"nama": "Musuk", "status": "Desa"},
            {"nama": "Sambirejo", "status": "Desa"},
            {"nama": "Sukorejo", "status": "Desa"},
            {"nama": "Jambeyan", "status": "Desa"},
            {"nama": "Dawung", "status": "Desa"},
            {"nama": "Srawung", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Sambungmacan",
        "daftar_wilayah": [
            {"nama": "Banaran", "status": "Desa"},
            {"nama": "Bedoro", "status": "Desa"},
            {"nama": "Cemeng", "status": "Desa"},
            {"nama": "Garingan", "status": "Desa"},
            {"nama": "Karanganyar", "status": "Desa"},
            {"nama": "Plumbon", "status": "Desa"},
            {"nama": "Sambungmacan", "status": "Desa"},
            {"nama": "Toyogo", "status": "Desa"},
            {"nama": "Kebonromo", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Sidoharjo",
        "daftar_wilayah": [
            {"nama": "Bentak", "status": "Desa"},
            {"nama": "Duyungan", "status": "Desa"},
            {"nama": "Jambanan", "status": "Desa"},
            {"nama": "Jetak", "status": "Desa"},
            {"nama": "Pandanpancur", "status": "Desa"},
            {"nama": "Patihan", "status": "Desa"},
            {"nama": "Purwosuman", "status": "Desa"},
            {"nama": "Sidoharjo", "status": "Desa"},
            {"nama": "Singojoyo", "status": "Desa"},
            {"nama": "Srikaya", "status": "Desa"},
            {"nama": "Taraman", "status": "Desa"},
            {"nama": "Tenggak", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Sukodono",
        "daftar_wilayah": [
            {"nama": "Baleharjo", "status": "Desa"},
            {"nama": "Bendo", "status": "Desa"},
            {"nama": "Gebbangan", "status": "Desa"},
            {"nama": "Juok", "status": "Desa"},
            {"nama": "Karanganom", "status": "Desa"},
            {"nama": "Majenang", "status": "Desa"},
            {"nama": "Newung", "status": "Desa"},
            {"nama": "Pantirejo", "status": "Desa"},
            {"nama": "Singojoyo", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Sumberlawang",
        "daftar_wilayah": [
            {"nama": "Hadiluwih", "status": "Desa"},
            {"nama": "Jati", "status": "Desa"},
            {"nama": "Kacangan", "status": "Desa"},
            {"nama": "Ngandul", "status": "Desa"},
            {"nama": "Pagak", "status": "Desa"},
            {"nama": "Pendem", "status": "Desa"},
            {"nama": "Mojopuro", "status": "Desa"},
            {"nama": "Trawas", "status": "Desa"},
            {"nama": "Gading", "status": "Desa"},
            {"nama": "Cepoko", "status": "Desa"},
            {"nama": "Boyolayar", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Tangen",
        "daftar_wilayah": [
            {"nama": "Dukuh", "status": "Desa"},
            {"nama": "Galeh", "status": "Desa"},
            {"nama": "Jekawal", "status": "Desa"},
            {"nama": "Katelan", "status": "Desa"},
            {"nama": "Ngepung", "status": "Desa"},
            {"nama": "Ngrombo", "status": "Desa"},
            {"nama": "Sigit", "status": "Desa"},
        ],
    },
    {
        "kecamatan": "Tanon",
        "daftar_wilayah": [
            {"nama": "Bonagung", "status": "Desa"},
            {"nama": "Gading", "status": "Desa"},
            {"nama": "Gabugan", "status": "Desa"},
            {"nama": "Jati", "status": "Desa"},
            {"nama": "Kalikobok", "status": "Desa"},
            {"nama": "Karangasem", "status": "Desa"},
            {"nama": "Karangtalun", "status": "Desa"},
            {"nama": "Kecik", "status": "Desa"},
            {"nama": "Ketro", "status": "Desa"},
            {"nama": "Padas", "status": "Desa"},
            {"nama": "Pengkol", "status": "Desa"},
            {"nama": "Sambiduwur", "status": "Desa"},
            {"nama": "Slogo", "status": "Desa"},
            {"nama": "Suwatu", "status": "Desa"},
            {"nama": "Tanon", "status": "Desa"},
            {"nama": "Warurejo", "status": "Desa"},
        ],
    },
]
